# Generated by Django 5.0.3 on 2024-03-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=5)),
                ('destination', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
            ],
        ),
    ]
