# Generated by Django 5.0.3 on 2024-04-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0003_alter_train_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='plan',
            new_name='adresse_plan',
        ),
    ]
